# Generated by Django 4.1 on 2024-11-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cabana', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(help_text='Capacidad máxima de personas')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento')], default='disponible', help_text='Estado de la cabaña', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Edicion')),
            ],
            options={
                'verbose_name': 'cabaña',
                'verbose_name_plural': 'cabañas',
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o descripción de la mantención', max_length=150)),
                ('fecha_ejecucion', models.DateTimeField(help_text='Fecha en la que se realizó la mantención')),
                ('responsable', models.CharField(help_text='Nombre del responsable de realizar la mantención', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='Detalles u observaciones adicionales', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Edicion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(help_text='RUT chileno, formato: 12.345.678-9', max_length=12, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('cliente', 'Cliente')], help_text='Rol del usuario dentro del sistema', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Edicion')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado de la reserva', max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Edicion')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='BD.cabana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='BD.usuario')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Edicion')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='BD.cabana')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='ActividadRecreativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fech. Edicion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='BD.reserva')),
            ],
            options={
                'verbose_name': 'actividad recreativa',
                'verbose_name_plural': 'actividades recreativas',
            },
        ),
    ]
