# Generated by Django 4.1 on 2024-11-17 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantencion',
            options={'verbose_name': 'Mantencion', 'verbose_name_plural': 'Mantenciones'},
        ),
    ]
