# Generated by Django 4.1 on 2024-11-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0002_alter_mantencion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabana',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
