# Generated by Django 4.1 on 2024-11-17 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0003_cabana_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabana',
            name='image',
        ),
        migrations.CreateModel(
            name='CabanaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/cabanas/', verbose_name='Imagen de la cabaña')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='BD.cabana', verbose_name='Cabaña')),
            ],
            options={
                'verbose_name': 'imagen de cabaña',
                'verbose_name_plural': 'imágenes de cabaña',
            },
        ),
    ]
