# Generated by Django 4.1 on 2024-12-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0004_remove_cabana_image_cabanaimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantencion',
            options={'verbose_name': 'Mantención', 'verbose_name_plural': 'Mantenciones'},
        ),
        migrations.AddField(
            model_name='mantencion',
            name='cabana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='BD.cabana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantencion',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado de la mantención', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='tipo',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva')], default='preventiva', help_text='Tipo de mantención', max_length=50),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='fecha_ejecucion',
            field=models.DateTimeField(help_text='Fecha en la que se realizó la mantención o está programada'),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
