# Generated by Django 5.1.3 on 2024-12-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0006_alter_reserva_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cabana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.cabana'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
