# Generated by Django 5.1.3 on 2024-12-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0007_alter_reserva_cabana_alter_reserva_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_total',
            field=models.IntegerField(default=0, help_text='Precio total de la reserva en pesos chilenos'),
            preserve_default=False,
        ),
    ]
