# Generated by Django 5.1.3 on 2024-12-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0008_reserva_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadrecreativa',
            name='reserva',
        ),
    ]
